name: pizza_repository
description: 'The Repo that handles users'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  firebase_core: ^2.16.0
    #firebase_auth: ^5.8.0
  cloud_firestore: ^4.9.2
#  firebase_storage: ^11.3.0
#  firebase_messaging: ^14.4.0
#  firebase_analytics: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
